# Generated by Django 3.1.4 on 2021-09-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingupLinkRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('role', models.TextField(default='')),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
