refreshtime: "30s"
macroStrategy: "tsrh_dc"
marketOpen: "09:32:00"
marketClose: "15:58:00"
botStartup: "09:25:00"
gatewayReset: "23:45:00"
liveTrading: "False"
emkt: "emkt" # "emkt" or "mkt" or "both"
dataSource: "Polygon" # "IB" or "Polygon" or "both"
broker: "alpaca"
sendTrades: "true" # whether to send trades to mongoDB or not
startingCashPerAccount: "10000"
mongoUrl: "mongodb+srv://chad:JWh1w8IFMBZcuq21@cluster0.35i8i.mongodb.net/backtesting_trades?retryWrites=true&w=majority"
