strategies:
 - "2 mins"
 - "12 mins"
 - "1 hour"
 - "4 hours"
 - "2 mins>1 hour"
 - "12 mins>1 hour"
 - "2 mins>4 hours"
 - "12 mins>4 hours"
 - "2 mins>12 mins>1 hour"
 - "2 mins>12 mins>4 hours"
 - "2 mins>12 mins>1 hour>4 hours"
