# Generated by Django 3.2.10 on 2022-06-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20211005_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scanner',
        ),
    ]
